services:
  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: kafka-broker
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes

  producer:
    image: python:3.11-slim
    container_name: standalone-producer
    working_dir: /backend
    volumes:
      - ./data:/backend/data
      - ./producer.py:/backend/producer.py
    command: >
      sh -c "pip install kafka-python numpy &&
      python -u /backend/producer.py"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    restart: on-failure

  consumer:
    image: python:3.11-slim
    container_name: standalone-consumer
    working_dir: /frontend
    volumes:
      - ./consumer.py:/frontend/consumer.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    command: >
      sh -c "pip install kafka-python numpy matplotlib pandas scikit-learn &&
      python -u /frontend/consumer.py"
    ports:
      - "8501:8501"
    restart: on-failure
